# Site settings
title: 苏克的博客
SEOTitle: 苏克的博客
header-img: img/1083822.jpg
email: ajksunke@gmail.com
description: "Personal blog about thinking in work and life."
keyword: "Ke Sun, Data Science, research, Artificial Intelligience, Statistics"
url: "http://datake.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/datake/datake.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "人的本质是一段时间.The Natue of a Person is a Period of Time."
sidebar-avatar: /img/github个人照片.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     sunke
zhihu_username:     孙科
#github_username:    sunke
#facebook_username:  sunke 
#jianshu_username:   ajksunke
#twitter_username:   ajksunke



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
#Disqus（https://disqus.com/）
#disqus_username: ajksunke

# Gitalk
gitalk:
  enable: false    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: datake.github.io    #仓库名称
  owner: datake    #github用户名
  admin: datake
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-124885050-1'            # Format: UA-xxxxxx-xx
ga_domain: auto              # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "新浪博客",
        href: "http://blog.sina.com.cn/u/5063351640"
    },{
        title: "CSDN博客",
        href: "https://blog.csdn.net/ajksunke"
    },{
        title: "Friend's blog",
        href: "https://ajksunkang.com"
    }
]
